python3 train.py --logs_file_path ../results/only_hospitalized_discretized_clinical_data/dt_1_feature_ftest_oversampling_results.csv --model DT_Classifier --dataset_path ../built_dataset/only_hospitalized_with_discretized_clinic_data.csv --balancing Oversampling --feature_retrieval SelectKBest --splitting Holdout --test_size 0.2 --nofsplits 5 --noftopfeatures 1 --preprocessing No --store_features_selection_report
python3 train.py --logs_file_path ../results/only_hospitalized_discretized_clinical_data/dt_2_feature_ftest_oversampling_results.csv --model DT_Classifier --dataset_path ../built_dataset/only_hospitalized_with_discretized_clinic_data.csv --balancing Oversampling --feature_retrieval SelectKBest --splitting Holdout --test_size 0.2 --nofsplits 5 --noftopfeatures 2 --preprocessing No --store_features_selection_report
python3 train.py --logs_file_path ../results/only_hospitalized_discretized_clinical_data/dt_3_feature_ftest_oversampling_results.csv --model DT_Classifier --dataset_path ../built_dataset/only_hospitalized_with_discretized_clinic_data.csv --balancing Oversampling --feature_retrieval SelectKBest --splitting Holdout --test_size 0.2 --nofsplits 5 --noftopfeatures 3 --preprocessing No --store_features_selection_report
python3 train.py --logs_file_path ../results/only_hospitalized_discretized_clinical_data/dt_5_feature_ftest_oversampling_results.csv --model DT_Classifier --dataset_path ../built_dataset/only_hospitalized_with_discretized_clinic_data.csv --balancing Oversampling --feature_retrieval SelectKBest --splitting Holdout --test_size 0.2 --nofsplits 5 --noftopfeatures 5 --preprocessing No --store_features_selection_report
python3 train.py --logs_file_path ../results/only_hospitalized_discretized_clinical_data/dt_10_feature_ftest_oversampling_results.csv --model DT_Classifier --dataset_path ../built_dataset/only_hospitalized_with_discretized_clinic_data.csv --balancing Oversampling --feature_retrieval SelectKBest --splitting Holdout --test_size 0.2 --nofsplits 5 --noftopfeatures 10 --preprocessing No --store_features_selection_report
python3 train.py --logs_file_path ../results/only_hospitalized_discretized_clinical_data/dt_15_feature_ftest_oversampling_results.csv --model DT_Classifier --dataset_path ../built_dataset/only_hospitalized_with_discretized_clinic_data.csv --balancing Oversampling --feature_retrieval SelectKBest --splitting Holdout --test_size 0.2 --nofsplits 5 --noftopfeatures 15 --preprocessing No --store_features_selection_report
python3 train.py --logs_file_path ../results/only_hospitalized_discretized_clinical_data/dt_20_feature_ftest_oversampling_results.csv --model DT_Classifier --dataset_path ../built_dataset/only_hospitalized_with_discretized_clinic_data.csv --balancing Oversampling --feature_retrieval SelectKBest --splitting Holdout --test_size 0.2 --nofsplits 5 --noftopfeatures 20 --preprocessing No --store_features_selection_report
python3 train.py --logs_file_path ../results/only_hospitalized_discretized_clinical_data/dt_25_feature_ftest_oversampling_results.csv --model DT_Classifier --dataset_path ../built_dataset/only_hospitalized_with_discretized_clinic_data.csv --balancing Oversampling --feature_retrieval SelectKBest --splitting Holdout --test_size 0.2 --nofsplits 5 --noftopfeatures 25 --preprocessing No --store_features_selection_report
python3 train.py --logs_file_path ../results/only_hospitalized_discretized_clinical_data/dt_all_feature_ftest_oversampling_results.csv --model DT_Classifier --dataset_path ../built_dataset/only_hospitalized_with_discretized_clinic_data.csv --balancing Oversampling --feature_retrieval No --splitting Holdout --test_size 0.2 --nofsplits 5 --preprocessing No --store_features_selection_report
