python3 train.py --logs_file_path ../results/only_hospitalized_zero_padding/dt_1_feature_ReliefF_oversampling_results.csv --model DT_Classifier --dataset_path ../built_dataset/only_hospitalized_zero_padding.csv --balancing Oversampling --feature_retrieval ReliefF --splitting Holdout --test_size 0.2 --nofsplits 5 --noftopfeatures 1 --preprocessing No --store_features_selection_report
python3 train.py --logs_file_path ../results/only_hospitalized_zero_padding/dt_2_feature_ReliefF_oversampling_results.csv --model DT_Classifier --dataset_path ../built_dataset/only_hospitalized_zero_padding.csv --balancing Oversampling --feature_retrieval ReliefF --splitting Holdout --test_size 0.2 --nofsplits 5 --noftopfeatures 2 --preprocessing No --store_features_selection_report
python3 train.py --logs_file_path ../results/only_hospitalized_zero_padding/dt_3_feature_ReliefF_oversampling_results.csv --model DT_Classifier --dataset_path ../built_dataset/only_hospitalized_zero_padding.csv --balancing Oversampling --feature_retrieval ReliefF --splitting Holdout --test_size 0.2 --nofsplits 5 --noftopfeatures 3 --preprocessing No --store_features_selection_report
python3 train.py --logs_file_path ../results/only_hospitalized_zero_padding/dt_5_feature_ReliefF_oversampling_results.csv --model DT_Classifier --dataset_path ../built_dataset/only_hospitalized_zero_padding.csv --balancing Oversampling --feature_retrieval ReliefF --splitting Holdout --test_size 0.2 --nofsplits 5 --noftopfeatures 5 --preprocessing No --store_features_selection_report
python3 train.py --logs_file_path ../results/only_hospitalized_zero_padding/dt_10_feature_ReliefF_oversampling_results.csv --model DT_Classifier --dataset_path ../built_dataset/only_hospitalized_zero_padding.csv --balancing Oversampling --feature_retrieval ReliefF --splitting Holdout --test_size 0.2 --nofsplits 5 --noftopfeatures 10 --preprocessing No --store_features_selection_report
python3 train.py --logs_file_path ../results/only_hospitalized_zero_padding/dt_15_feature_ReliefF_oversampling_results.csv --model DT_Classifier --dataset_path ../built_dataset/only_hospitalized_zero_padding.csv --balancing Oversampling --feature_retrieval ReliefF --splitting Holdout --test_size 0.2 --nofsplits 5 --noftopfeatures 15 --preprocessing No --store_features_selection_report
python3 train.py --logs_file_path ../results/only_hospitalized_zero_padding/dt_20_feature_ReliefF_oversampling_results.csv --model DT_Classifier --dataset_path ../built_dataset/only_hospitalized_zero_padding.csv --balancing Oversampling --feature_retrieval ReliefF --splitting Holdout --test_size 0.2 --nofsplits 5 --noftopfeatures 20 --preprocessing No --store_features_selection_report
python3 train.py --logs_file_path ../results/only_hospitalized_zero_padding/dt_25_feature_ReliefF_oversampling_results.csv --model DT_Classifier --dataset_path ../built_dataset/only_hospitalized_zero_padding.csv --balancing Oversampling --feature_retrieval ReliefF --splitting Holdout --test_size 0.2 --nofsplits 5 --noftopfeatures 25 --preprocessing No --store_features_selection_report
python3 train.py --logs_file_path ../results/only_hospitalized_zero_padding/dt_all_feature_ReliefF_oversampling_results.csv --model DT_Classifier --dataset_path ../built_dataset/only_hospitalized_zero_padding.csv --balancing Oversampling --feature_retrieval No --splitting Holdout --test_size 0.2 --nofsplits 5 --preprocessing No --store_features_selection_report
