python3 train.py --logs_file_path ../results/only_hospitalized/svm_1_feature_ReliefF_oversampling_results.csv --classifier SVM --dataset_path ../built_dataset/only_hospitalized.csv --balancing Oversampling --feature_retrieval ReliefF --splitting Holdout --test_size 0.2 --nofrepetitions 5 --noftopfeatures 1
python3 train.py --logs_file_path ../results/only_hospitalized/svm_2_features_ReliefF_oversampling_results.csv --classifier SVM --dataset_path ../built_dataset/only_hospitalized.csv --balancing Oversampling --feature_retrieval ReliefF --splitting Holdout --test_size 0.2 --nofrepetitions 5 --noftopfeatures 2
python3 train.py --logs_file_path ../results/only_hospitalized/svm_3_features_ReliefF_oversampling_results.csv --classifier SVM --dataset_path ../built_dataset/only_hospitalized.csv --balancing Oversampling --feature_retrieval ReliefF --splitting Holdout --test_size 0.2 --nofrepetitions 5 --noftopfeatures 3
python3 train.py --logs_file_path ../results/only_hospitalized/svm_5_features_ReliefF_oversampling_results.csv --classifier SVM --dataset_path ../built_dataset/only_hospitalized.csv --balancing Oversampling --feature_retrieval ReliefF --splitting Holdout --test_size 0.2 --nofrepetitions 5 --noftopfeatures 5
python3 train.py --logs_file_path ../results/only_hospitalized/svm_10_features_ReliefF_oversampling_results.csv --classifier SVM --dataset_path ../built_dataset/only_hospitalized.csv --balancing Oversampling --feature_retrieval ReliefF --splitting Holdout --test_size 0.2 --nofrepetitions 5 --noftopfeatures 10
python3 train.py --logs_file_path ../results/only_hospitalized/svm_15_features_ReliefF_oversampling_results.csv --classifier SVM --dataset_path ../built_dataset/only_hospitalized.csv --balancing Oversampling --feature_retrieval ReliefF --splitting Holdout --test_size 0.2 --nofrepetitions 5 --noftopfeatures 15
python3 train.py --logs_file_path ../results/only_hospitalized/svm_20_features_ReliefF_oversampling_results.csv --classifier SVM --dataset_path ../built_dataset/only_hospitalized.csv --balancing Oversampling --feature_retrieval ReliefF --splitting Holdout --test_size 0.2 --nofrepetitions 5 --noftopfeatures 20
python3 train.py --logs_file_path ../results/only_hospitalized/svm_25_features_ReliefF_oversampling_results.csv --classifier SVM --dataset_path ../built_dataset/only_hospitalized.csv --balancing Oversampling --feature_retrieval ReliefF --splitting Holdout --test_size 0.2 --nofrepetitions 5 --noftopfeatures 25
python3 train.py --logs_file_path ../results/only_hospitalized/svm_all_features_ReliefF_oversampling_results.csv --classifier SVM --dataset_path ../built_dataset/only_hospitalized.csv --balancing Oversampling --feature_retrieval No --splitting Holdout --test_size 0.2 --nofrepetitions 5
