python3 train.py --logs_file_path ../results/only_hospitalized/dt_1_feature_PCA_oversampling_results.csv --model DT_Classifier --dataset_path ../built_dataset/only_hospitalized.csv --balancing Oversampling --feature_retrieval PCA --splitting Holdout --test_size 0.2 --nofsplits 5 --nofcomponents 1 --preprocessing No
python3 train.py --logs_file_path ../results/only_hospitalized/dt_2_feature_PCA_oversampling_results.csv --model DT_Classifier --dataset_path ../built_dataset/only_hospitalized.csv --balancing Oversampling --feature_retrieval PCA --splitting Holdout --test_size 0.2 --nofsplits 5 --nofcomponents 2 --preprocessing No
python3 train.py --logs_file_path ../results/only_hospitalized/dt_3_feature_PCA_oversampling_results.csv --model DT_Classifier --dataset_path ../built_dataset/only_hospitalized.csv --balancing Oversampling --feature_retrieval PCA --splitting Holdout --test_size 0.2 --nofsplits 5 --nofcomponents 3 --preprocessing No
python3 train.py --logs_file_path ../results/only_hospitalized/dt_5_feature_PCA_oversampling_results.csv --model DT_Classifier --dataset_path ../built_dataset/only_hospitalized.csv --balancing Oversampling --feature_retrieval PCA --splitting Holdout --test_size 0.2 --nofsplits 5 --nofcomponents 5 --preprocessing No
python3 train.py --logs_file_path ../results/only_hospitalized/dt_10_feature_PCA_oversampling_results.csv --model DT_Classifier --dataset_path ../built_dataset/only_hospitalized.csv --balancing Oversampling --feature_retrieval PCA --splitting Holdout --test_size 0.2 --nofsplits 5 --nofcomponents 10 --preprocessing No
python3 train.py --logs_file_path ../results/only_hospitalized/dt_15_feature_PCA_oversampling_results.csv --model DT_Classifier --dataset_path ../built_dataset/only_hospitalized.csv --balancing Oversampling --feature_retrieval PCA --splitting Holdout --test_size 0.2 --nofsplits 5 --nofcomponents 15 --preprocessing No
python3 train.py --logs_file_path ../results/only_hospitalized/dt_20_feature_PCA_oversampling_results.csv --model DT_Classifier --dataset_path ../built_dataset/only_hospitalized.csv --balancing Oversampling --feature_retrieval PCA --splitting Holdout --test_size 0.2 --nofsplits 5 --nofcomponents 20 --preprocessing No
python3 train.py --logs_file_path ../results/only_hospitalized/dt_25_feature_PCA_oversampling_results.csv --model DT_Classifier --dataset_path ../built_dataset/only_hospitalized.csv --balancing Oversampling --feature_retrieval PCA --splitting Holdout --test_size 0.2 --nofsplits 5 --nofcomponents 25 --preprocessing No
python3 train.py --logs_file_path ../results/only_hospitalized/dt_all_feature_PCA_oversampling_results.csv --model DT_Classifier --dataset_path ../built_dataset/only_hospitalized.csv --balancing Oversampling --feature_retrieval No --splitting Holdout --test_size 0.2 --nofsplits 5 --preprocessing No
