python3 train.py --logs_file_path ../results/only_hospitalized_urgency_time/dt_1_feature_ReliefF_oversampling_results.csv --model Linear_Regressor --dataset_path ../built_dataset/only_hospitalized_with_urgency_time.csv --balancing No --feature_retrieval ReliefF --splitting Holdout --test_size 0.2 --nofrepetitions 5 --noftopfeatures 1
python3 train.py --logs_file_path ../results/only_hospitalized_urgency_time/dt_2_feature_ReliefF_oversampling_results.csv --model Linear_Regressor --dataset_path ../built_dataset/only_hospitalized_with_urgency_time.csv --balancing No --feature_retrieval ReliefF --splitting Holdout --test_size 0.2 --nofrepetitions 5 --noftopfeatures 2
python3 train.py --logs_file_path ../results/only_hospitalized_urgency_time/dt_3_feature_ReliefF_oversampling_results.csv --model Linear_Regressor --dataset_path ../built_dataset/only_hospitalized_with_urgency_time.csv --balancing No --feature_retrieval ReliefF --splitting Holdout --test_size 0.2 --nofrepetitions 5 --noftopfeatures 3
python3 train.py --logs_file_path ../results/only_hospitalized_urgency_time/dt_5_feature_ReliefF_oversampling_results.csv --model Linear_Regressor --dataset_path ../built_dataset/only_hospitalized_with_urgency_time.csv --balancing No --feature_retrieval ReliefF --splitting Holdout --test_size 0.2 --nofrepetitions 5 --noftopfeatures 5
python3 train.py --logs_file_path ../results/only_hospitalized_urgency_time/dt_10_feature_ReliefF_oversampling_results.csv --model Linear_Regressor --dataset_path ../built_dataset/only_hospitalized_with_urgency_time.csv --balancing No --feature_retrieval ReliefF --splitting Holdout --test_size 0.2 --nofrepetitions 5 --noftopfeatures 10
python3 train.py --logs_file_path ../results/only_hospitalized_urgency_time/dt_15_feature_ReliefF_oversampling_results.csv --model Linear_Regressor --dataset_path ../built_dataset/only_hospitalized_with_urgency_time.csv --balancing No --feature_retrieval ReliefF --splitting Holdout --test_size 0.2 --nofrepetitions 5 --noftopfeatures 15
python3 train.py --logs_file_path ../results/only_hospitalized_urgency_time/dt_20_feature_ReliefF_oversampling_results.csv --model Linear_Regressor --dataset_path ../built_dataset/only_hospitalized_with_urgency_time.csv --balancing No --feature_retrieval ReliefF --splitting Holdout --test_size 0.2 --nofrepetitions 5 --noftopfeatures 20
python3 train.py --logs_file_path ../results/only_hospitalized_urgency_time/dt_25_feature_ReliefF_oversampling_results.csv --model Linear_Regressor --dataset_path ../built_dataset/only_hospitalized_with_urgency_time.csv --balancing No --feature_retrieval ReliefF --splitting Holdout --test_size 0.2 --nofrepetitions 5 --noftopfeatures 25
python3 train.py --logs_file_path ../results/only_hospitalized_urgency_time/dt_all_feature_ReliefF_oversampling_results.csv --model Linear_Regressor --dataset_path ../built_dataset/only_hospitalized_with_urgency_time.csv --balancing No --feature_retrieval No --splitting Holdout --test_size 0.2 --nofrepetitions 5
