python3 train.py --logs_file_path ../results/hospitalized_and_urgencies/dt_1_feature_PCA_oversampling_results.csv --model DT_Classifer --dataset_path ../built_dataset/hospitalized_and_urgencies.csv --balancing Oversampling --feature_retrieval PCA --splitting Holdout --test_size 0.2 --nofsplits 5 --nofcomponents 1 --preprocessing No
python3 train.py --logs_file_path ../results/hospitalized_and_urgencies/dt_2_features_PCA_oversampling_results.csv --model DT_Classifer --dataset_path ../built_dataset/hospitalized_and_urgencies.csv --balancing Oversampling --feature_retrieval PCA --splitting Holdout --test_size 0.2 --nofsplits 5 --nofcomponents 2 --preprocessing No
python3 train.py --logs_file_path ../results/hospitalized_and_urgencies/dt_3_features_PCA_oversampling_results.csv --model DT_Classifer --dataset_path ../built_dataset/hospitalized_and_urgencies.csv --balancing Oversampling --feature_retrieval PCA --splitting Holdout --test_size 0.2 --nofsplits 5 --nofcomponents 3 --preprocessing No
python3 train.py --logs_file_path ../results/hospitalized_and_urgencies/dt_5_features_PCA_oversampling_results.csv --model DT_Classifer --dataset_path ../built_dataset/hospitalized_and_urgencies.csv --balancing Oversampling --feature_retrieval PCA --splitting Holdout --test_size 0.2 --nofsplits 5 --nofcomponents 5 --preprocessing No
python3 train.py --logs_file_path ../results/hospitalized_and_urgencies/dt_10_features_PCA_oversampling_results.csv --model DT_Classifer --dataset_path ../built_dataset/hospitalized_and_urgencies.csv --balancing Oversampling --feature_retrieval PCA --splitting Holdout --test_size 0.2 --nofsplits 5 --nofcomponents 10 --preprocessing No
python3 train.py --logs_file_path ../results/hospitalized_and_urgencies/dt_15_features_PCA_oversampling_results.csv --model DT_Classifer --dataset_path ../built_dataset/hospitalized_and_urgencies.csv --balancing Oversampling --feature_retrieval PCA --splitting Holdout --test_size 0.2 --nofsplits 5 --nofcomponents 15 --preprocessing No
python3 train.py --logs_file_path ../results/hospitalized_and_urgencies/dt_20_features_PCA_oversampling_results.csv --model DT_Classifer --dataset_path ../built_dataset/hospitalized_and_urgencies.csv --balancing Oversampling --feature_retrieval PCA --splitting Holdout --test_size 0.2 --nofsplits 5 --nofcomponents 20 --preprocessing No
python3 train.py --logs_file_path ../results/hospitalized_and_urgencies/dt_25_features_PCA_oversampling_results.csv --model DT_Classifer --dataset_path ../built_dataset/hospitalized_and_urgencies.csv --balancing Oversampling --feature_retrieval PCA --splitting Holdout --test_size 0.2 --nofsplits 5 --nofcomponents 25 --preprocessing No

