python3 train.py --logs_file_path ../results/only_hospitalized/dt_1_feature_ReliefF_oversampling_results.csv --classifier DT --dataset_path ../built_dataset/only_hospitalized.csv --balancing Oversampling --feature_retrieval ReliefF --splitting Holdout --test_size 0.2 --nofrepetitions 5 --noftopfeatures 1
python3 train.py --logs_file_path ../results/only_hospitalized/dt_2_feature_ReliefF_oversampling_results.csv --classifier DT --dataset_path ../built_dataset/only_hospitalized.csv --balancing Oversampling --feature_retrieval ReliefF --splitting Holdout --test_size 0.2 --nofrepetitions 5 --noftopfeatures 2
python3 train.py --logs_file_path ../results/only_hospitalized/dt_3_feature_ReliefF_oversampling_results.csv --classifier DT --dataset_path ../built_dataset/only_hospitalized.csv --balancing Oversampling --feature_retrieval ReliefF --splitting Holdout --test_size 0.2 --nofrepetitions 5 --noftopfeatures 3
python3 train.py --logs_file_path ../results/only_hospitalized/dt_5_feature_ReliefF_oversampling_results.csv --classifier DT --dataset_path ../built_dataset/only_hospitalized.csv --balancing Oversampling --feature_retrieval ReliefF --splitting Holdout --test_size 0.2 --nofrepetitions 5 --noftopfeatures 5
python3 train.py --logs_file_path ../results/only_hospitalized/dt_10_feature_ReliefF_oversampling_results.csv --classifier DT --dataset_path ../built_dataset/only_hospitalized.csv --balancing Oversampling --feature_retrieval ReliefF --splitting Holdout --test_size 0.2 --nofrepetitions 5 --noftopfeatures 10
python3 train.py --logs_file_path ../results/only_hospitalized/dt_15_feature_ReliefF_oversampling_results.csv --classifier DT --dataset_path ../built_dataset/only_hospitalized.csv --balancing Oversampling --feature_retrieval ReliefF --splitting Holdout --test_size 0.2 --nofrepetitions 5 --noftopfeatures 15
python3 train.py --logs_file_path ../results/only_hospitalized/dt_20_feature_ReliefF_oversampling_results.csv --classifier DT --dataset_path ../built_dataset/only_hospitalized.csv --balancing Oversampling --feature_retrieval ReliefF --splitting Holdout --test_size 0.2 --nofrepetitions 5 --noftopfeatures 20
python3 train.py --logs_file_path ../results/only_hospitalized/dt_25_feature_ReliefF_oversampling_results.csv --classifier DT --dataset_path ../built_dataset/only_hospitalized.csv --balancing Oversampling --feature_retrieval ReliefF --splitting Holdout --test_size 0.2 --nofrepetitions 5 --noftopfeatures 25
python3 train.py --logs_file_path ../results/only_hospitalized/dt_all_feature_ReliefF_oversampling_results.csv --classifier DT --dataset_path ../built_dataset/only_hospitalized.csv --balancing Oversampling --feature_retrieval No --splitting Holdout --test_size 0.2 --nofrepetitions 5
