python3 train.py --logs_file_path ../results/only_hospitalized/svm_1_feature_ReliefF_oversampling_results.csv --model SVM_Classifier --dataset_path ../built_dataset/only_hospitalized.csv --balancing Oversampling --feature_retrieval ReliefF --splitting Holdout --test_size 0.2 --nofsplits 5 --noftopfeatures 1 --preprocessing No
python3 train.py --logs_file_path ../results/only_hospitalized/svm_2_features_ReliefF_oversampling_results.csv --model SVM_Classifier --dataset_path ../built_dataset/only_hospitalized.csv --balancing Oversampling --feature_retrieval ReliefF --splitting Holdout --test_size 0.2 --nofsplits 5 --noftopfeatures 2 --preprocessing No
python3 train.py --logs_file_path ../results/only_hospitalized/svm_3_features_ReliefF_oversampling_results.csv --model SVM_Classifier --dataset_path ../built_dataset/only_hospitalized.csv --balancing Oversampling --feature_retrieval ReliefF --splitting Holdout --test_size 0.2 --nofsplits 5 --noftopfeatures 3 --preprocessing No
python3 train.py --logs_file_path ../results/only_hospitalized/svm_5_features_ReliefF_oversampling_results.csv --model SVM_Classifier --dataset_path ../built_dataset/only_hospitalized.csv --balancing Oversampling --feature_retrieval ReliefF --splitting Holdout --test_size 0.2 --nofsplits 5 --noftopfeatures 5 --preprocessing No
python3 train.py --logs_file_path ../results/only_hospitalized/svm_10_features_ReliefF_oversampling_results.csv --model SVM_Classifier --dataset_path ../built_dataset/only_hospitalized.csv --balancing Oversampling --feature_retrieval ReliefF --splitting Holdout --test_size 0.2 --nofsplits 5 --noftopfeatures 10 --preprocessing No
python3 train.py --logs_file_path ../results/only_hospitalized/svm_15_features_ReliefF_oversampling_results.csv --model SVM_Classifier --dataset_path ../built_dataset/only_hospitalized.csv --balancing Oversampling --feature_retrieval ReliefF --splitting Holdout --test_size 0.2 --nofsplits 5 --noftopfeatures 15 --preprocessing No
python3 train.py --logs_file_path ../results/only_hospitalized/svm_20_features_ReliefF_oversampling_results.csv --model SVM_Classifier --dataset_path ../built_dataset/only_hospitalized.csv --balancing Oversampling --feature_retrieval ReliefF --splitting Holdout --test_size 0.2 --nofsplits 5 --noftopfeatures 20 --preprocessing No
python3 train.py --logs_file_path ../results/only_hospitalized/svm_25_features_ReliefF_oversampling_results.csv --model SVM_Classifier --dataset_path ../built_dataset/only_hospitalized.csv --balancing Oversampling --feature_retrieval ReliefF --splitting Holdout --test_size 0.2 --nofsplits 5 --noftopfeatures 25 --preprocessing No
python3 train.py --logs_file_path ../results/only_hospitalized/svm_all_features_ReliefF_oversampling_results.csv --model SVM_Classifier --dataset_path ../built_dataset/only_hospitalized.csv --balancing Oversampling --feature_retrieval No --splitting Holdout --test_size 0.2 --nofsplits 5 --preprocessing No
