python3 train.py --logs_file_path ../results/only_hospitalized/dt_1_feature_PCA_oversampling_results.csv --model DT_Classifier --dataset_path ../built_dataset/only_hospitalized.csv --balancing Oversampling --feature_retrieval PCA --splitting Holdout --test_size 0.2 --nofrepetitions 5 --nofcomponents 1
python3 train.py --logs_file_path ../results/only_hospitalized/dt_2_feature_PCA_oversampling_results.csv --model DT_Classifier --dataset_path ../built_dataset/only_hospitalized.csv --balancing Oversampling --feature_retrieval PCA --splitting Holdout --test_size 0.2 --nofrepetitions 5 --nofcomponents 2
python3 train.py --logs_file_path ../results/only_hospitalized/dt_3_feature_PCA_oversampling_results.csv --model DT_Classifier --dataset_path ../built_dataset/only_hospitalized.csv --balancing Oversampling --feature_retrieval PCA --splitting Holdout --test_size 0.2 --nofrepetitions 5 --nofcomponents 3
python3 train.py --logs_file_path ../results/only_hospitalized/dt_5_feature_PCA_oversampling_results.csv --model DT_Classifier --dataset_path ../built_dataset/only_hospitalized.csv --balancing Oversampling --feature_retrieval PCA --splitting Holdout --test_size 0.2 --nofrepetitions 5 --nofcomponents 5
python3 train.py --logs_file_path ../results/only_hospitalized/dt_10_feature_PCA_oversampling_results.csv --model DT_Classifier --dataset_path ../built_dataset/only_hospitalized.csv --balancing Oversampling --feature_retrieval PCA --splitting Holdout --test_size 0.2 --nofrepetitions 5 --nofcomponents 10
python3 train.py --logs_file_path ../results/only_hospitalized/dt_15_feature_PCA_oversampling_results.csv --model DT_Classifier --dataset_path ../built_dataset/only_hospitalized.csv --balancing Oversampling --feature_retrieval PCA --splitting Holdout --test_size 0.2 --nofrepetitions 5 --nofcomponents 15
python3 train.py --logs_file_path ../results/only_hospitalized/dt_20_feature_PCA_oversampling_results.csv --model DT_Classifier --dataset_path ../built_dataset/only_hospitalized.csv --balancing Oversampling --feature_retrieval PCA --splitting Holdout --test_size 0.2 --nofrepetitions 5 --nofcomponents 20
python3 train.py --logs_file_path ../results/only_hospitalized/dt_25_feature_PCA_oversampling_results.csv --model DT_Classifier --dataset_path ../built_dataset/only_hospitalized.csv --balancing Oversampling --feature_retrieval PCA --splitting Holdout --test_size 0.2 --nofrepetitions 5 --nofcomponents 25
python3 train.py --logs_file_path ../results/only_hospitalized/dt_all_feature_PCA_oversampling_results.csv --model DT_Classifier --dataset_path ../built_dataset/only_hospitalized.csv --balancing Oversampling --feature_retrieval No --splitting Holdout --test_size 0.2 --nofrepetitions 5
